---

controller_execution_environments:
  
  - name: Product Demo EE
    description: Ansible Product Demos Execution Environment
    image: quay.io/ansible-product-demos/apd-ee-25:20251013

  - name: ServiceNow EE
    description: ServiceNow Execution Environment
    image: quay.io/dperrone/servicenow_ee:20251107

  - name: VMWare EE
    description: VMWare Execution Environment
    image: quay.io/dperrone/vmware_ee:20250925

  - name: Windows EE
    description: Windows Execution Environment
    image: quay.io/dperrone/windows_ee:20251007